# Generated by Django 4.2.6 on 2023-10-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_alter_interview_date_for_interview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
